In [1]:
import IPython
print(Ipython.__version__)

NameError: name 'Ipython' is not defined

In [2]:
import numpy as np
print(np.__version__)

1.11.3


In [3]:
import bs4
print(bs4.__version__)

4.5.3


In [4]:
import sklearn
print(sklearn.__version__)

0.18.1


In [5]:
import requests
print(requests.__version__)

2.12.4


In [9]:
import pyquery
print('Loaded PyQuery')

Loaded PyQuery


In [8]:
pip install pyquery

SyntaxError: invalid syntax (<ipython-input-8-2dc49226c8a9>, line 1)

In [11]:
np.random.randn(2,2)

array([[-0.52081751,  0.63413075],
       [-0.25937055, -0.2818609 ]])

In [12]:
import seaborn as sns
print('seaborn loaded')

seaborn loaded


In [15]:
x=np.random.random((3,4))
x

array([[ 0.08384299,  0.38559981,  0.99431486,  0.65939421],
       [ 0.47795153,  0.62173811,  0.05849053,  0.01965098],
       [ 0.54493551,  0.14087296,  0.90102875,  0.65701547]])

In [16]:
x+1

array([[ 1.08384299,  1.38559981,  1.99431486,  1.65939421],
       [ 1.47795153,  1.62173811,  1.05849053,  1.01965098],
       [ 1.54493551,  1.14087296,  1.90102875,  1.65701547]])

In [17]:
x[1,2]

0.058490533998006189

In [18]:
x.max()

0.99431486345179276

In [19]:
x.min()

0.019650984620312673

In [20]:
x.mean()

0.46206964377270698

In [21]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which ca

In [23]:
def simulate_prizedoor(nsim):
    return np.random.randint(0,3,nsim)
simulate_prizedoor(5)

array([1, 2, 1, 1, 1])

In [25]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [26]:
def simulate_guess(nsim):
    return np.zeros(nsim,dtype=np.int)
simulate_guess(5)

array([0, 0, 0, 0, 0])